### ISSUE TITLE
Build issues for windows

### ISSUE THREAD

**Issue by TheMartynBliss** [logicomacorp/WaveSabre#28]
CMake -B build didn't work on windows 10. 
cmake . (in the wavesabre directory did)
but, I get one error:
WaveSabreVstLib.lib(vstplugmain.obj) : error LNK2019: unresolved external symbol "class AudioEffect * __cdecl createEffectInstance(int (__cdecl*)(struct AEffect *,int,int,int,void *,float))" (?createEffectInstance@@YAPAVAudioEffect@@P6AHPAUAEffect@@HHHPAXM@Z@Z) referenced in function _MAIN
1>

**Comment by h0ffman** [comment]
Hey @TheMartynBliss it looks like you don't have the VST SDK or if you do it's in the wrong folder.  CMake won't be able to build the project files until its there.

**Comment by TheMartynBliss** [comment]
Yes, I had copied it in, but didn't re-run the cmake…. Doh!
