### ISSUE TITLE
Add preset system

### ISSUE THREAD

**Issue by lamogui** [logicomacorp/WaveSabre#31]
Hello @yupferris 

With a musician we are really thinking to use this master piece synth for our next 64k intro.
He want to have the ability to save preset of each synth (he is using renoise), so I created this issue with a plan to complete it later. I posted the issue here as a reminder because I don't find a issue panel on my fork, if it bother tell me I will remove it.

lamogui

**Comment by yupferris** [comment]
Hi!

[Issues can be enabled on github forks in the settings panel](https://softwareengineering.stackexchange.com/a/179470).
