### ISSUE TITLE
Fix out-of-the-box vs2019 support for x86

### ISSUE THREAD

**Issue by yupferris** [logicomacorp/WaveSabre#59]
While x64 appears to work without fuss, x86 builds seem to rely on some MSVCRT functions that we have incorrect definitions for - particularly, `_alldiv`, `_allmul`, and `_allshl`. I've verified that when using the old `msvcrt_old.lib` file that we used to ship as a binary blob, we could get things to work. I also tried to shim them in by hand with code from [here](https://www-user.tu-chemnitz.de/~heha/viewzip.php/hsn/msvcrt-light.zip/src/) (with some project config changes outlined [here](https://stackoverflow.com/questions/33751509/external-assembly-file-in-visual-studio)) and that also works, though I don't just want to copy that code for copyright reasons (though I'm not sure how else we can make similar shims in a nice way, maybe in C?).

To be fair, I do have working x64 [squishy](http://logicoma.io/squishy/) builds, and there was even one WS exemusic entry released using it already. It would be _really great_ if we could just start focusing on x64 and drop x86 altogether. However, the packer alone just isn't enough; I haven't gotten x64 compression on par with x86 and I'm suspecting we won't be able to close the gap as much as I'd hoped, as the code is just denser. So, I think we're stuck supporting both for the time being.

**Comment by yupferris** [comment]
Note that I didn't actually explore where/why these are imported now and weren't before, and perhaps there's a simple workaround if we can figure that out and avoid it.

**Comment by yupferris** [comment]
`_alldiv` and `_allmul` both come from this line: https://github.com/logicomacorp/WaveSabre/blob/master/WaveSabrePlayerLib/src/DirectSoundRenderThread.cpp#L52

`_allshl` comes from this line: https://github.com/logicomacorp/WaveSabre/blob/master/WaveSabreCore/src/Helpers.cpp#L149

**Comment by kusma** [comment]
These are about signed 64 integer mismatch between the C/C++ ABI and x86. I believe we can fix them by casting to unsigned in the right places.

**Comment by kusma** [comment]
The second case seems like it's a performance disaster to end up in the `_allshl` codepath in the first place.

I would say some optimization rules has changed in the compiler, meaning it's no longer able to avoid these calls. I wouldn't be too surprised, x86 is no longer an important optimization target for most types of applications, so it might be a risky venue to use a new compiler for it...

**Comment by yupferris** [comment]
I also wouldn’t be entirely against not officially supporting x86 for vs2019 onwards and pushing x64 as the default everywhere once squishy x64 is available, fwiw. I really want x64 to be default everywhere.

That said, it’s still probably worth looking for workaround(s) and I also have a patch to turn these errors at runtime into link errors.

**Comment by yupferris** [comment]
re `_allmul`/`_alldiv`, I think it's enough just to make `DirectSoundRenderThread::GetPlayPositionMs` return `unsigned int` and perform the mul/div unsigned as follows:

```diff
diff --git a/WaveSabrePlayerLib/include/WaveSabrePlayerLib/DirectSoundRenderThread.h b/WaveSabrePlayerLib/include/WaveSabrePlayerLib/DirectSoundRenderThread.h
index f54d1d7..3d68c30 100644
--- a/WaveSabrePlayerLib/include/WaveSabrePlayerLib/DirectSoundRenderThread.h
+++ b/WaveSabrePlayerLib/include/WaveSabrePlayerLib/DirectSoundRenderThread.h
@@ -17,7 +17,7 @@ namespace WaveSabrePlayerLib
                DirectSoundRenderThread(RenderCallback callback, void *callbackData, int sampleRate, int bufferSizeMs = 1000);
                ~DirectSoundRenderThread();

-               int GetPlayPositionMs();
+               unsigned int GetPlayPositionMs();

        private:
                static DWORD WINAPI threadProc(LPVOID lpParameter);
diff --git a/WaveSabrePlayerLib/src/DirectSoundRenderThread.cpp b/WaveSabrePlayerLib/src/DirectSoundRenderThread.cpp
index fd50a11..dae28eb 100644
--- a/WaveSabrePlayerLib/src/DirectSoundRenderThread.cpp
+++ b/WaveSabrePlayerLib/src/DirectSoundRenderThread.cpp
@@ -26,7 +26,7 @@ namespace WaveSabrePlayerLib
                WaitForSingleObject(thread, INFINITE);
        }

-       int DirectSoundRenderThread::GetPlayPositionMs()
+       unsigned int DirectSoundRenderThread::GetPlayPositionMs()
        {
                if (!buffer)
                        return 0;
@@ -49,7 +49,7 @@ namespace WaveSabrePlayerLib
                        totalBytesRead += bufferSizeBytes;
                totalBytesRead += currentBytesRendered;

-               return (int)(totalBytesRead / SongRenderer::BlockAlign * 1000 / sampleRate);
+               return (unsigned int)((unsigned long long)totalBytesRead / SongRenderer::BlockAlign * 1000 / sampleRate);
        }

        DWORD WINAPI DirectSoundRenderThread::threadProc(LPVOID lpParameter)
```

Alternatively, instead of keeping total bytes rendered in 64 bits, we could keep track of two 32-bit unsigned quantities, ms rendered, and fractional ms rendered, with enough precision to match our sample rate. This is more complicated/error-prone, though.

**Comment by yupferris** [comment]
Getting rid of `_allshl` is, surprisingly, a bit more tricky. It doesn't seem to matter whether or not `phaseAsInt` is signed or unsigned (which makes sense, since it's a left shift); so far I haven't been able to work around it without decidedly losing precision.

(side note: there's a bit of irony in that [reverting some of the sinusoid operations that I dug into last night](#57) may have allowed us to work around this easier, but I don't think that's a good enough reason to back out of the change still :) .)

**Comment by yupferris** [comment]
re my comment earlier:
> edit: it may not be; we have 53 bits in double, so we could likely just keep track of how many samples have been rendered with that type, and return that all the way until the function that returns seconds, and just convert there, and we likely have several bits more than we need

I looked into this, and it turns out it's not actually simpler overall, since `PreRenderPlayer` also does some calculations in ms, so it's simpler to have the conversion from bytes rendered -> ms rendered in one place.

**Comment by yupferris** [comment]
Hey wait a minute! Since we already fixed the double phase to be in the `[1, 2)` range, wouldn’t that mean its exponent is fixed? So we actually shouldn’t need the left shift at all (or at the very least that it’s constant and we can factor it another way)?

**Comment by yupferris** [comment]
Ah, that _would_ be true but we actually only guarantee the lower bound.

**Comment by yupferris** [comment]
OK, I was wrong about the `GetPlayPositionMs` patch above - once I hacked a workaround for `_allshl` it actually failed at runtime again, this time with `__aulldiv`, again in `GetPlayPositionMs`. This is feeling a bit futile.

**Comment by yupferris** [comment]
ha, ok, I actually found a configuration that works. Turns out `_allshl` isn't required with `/O2` (optimize for speed), and if I use `double` for all of the time tracking in `DirectSoundRenderThread`, neither are the other long-related ops.

**Comment by kusma** [comment]
Nice catch!
Move the code to the end of the source-file and do
`#pragma optimize( "s", on)` right before? :P

**Comment by kusma** [comment]
More seriously, we should probably look at what code is generated in the case that don't need it; maybe the compiler realize we don't really need this shift to be 64-bits for some reason?

**Comment by yupferris** [comment]
This is with `/O2`:

```
		auto significand = (unsigned int)((phaseAsInt << exponent) >> (52 - 32));
00406A78  movq        xmm1,mmword ptr [phaseAsInt]  
00406A7D  shr         eax,14h  
00406A80  sub         eax,3FFh  
00406A85  movd        xmm0,eax  
00406A89  psllq       xmm1,xmm0  
00406A8D  psrlq       xmm1,14h  
00406A92  movd        ecx,xmm1  
```

The first couple lines determine the `exponent`, then there's the shifts. It seems both shifts (left and right) are still there, it's just that they use SSE2.

**Comment by yupferris** [comment]
UGH, after making the PR I decided to test x64 again, and ofc, it's broken, likely due to `/O2`: `unresolved external symbol __vdecl_cos2`. And if I change back to `/01`, `__imp_floorf` and `__imp_sqrtf` are missing instead, which is actually strange, as I thought I had this working a few months ago...

**Comment by yupferris** [comment]
Yeah so master works, yet my branch doesn't, even if I manually change `WaveSabreCore` to use `/Oi` again and rebuild. This is really fucked.

**Comment by yupferris** [comment]
I _guess_ we could make the `/Oi`/`/O2` option dependent on the target platform...

**Comment by yupferris** [comment]
OK - I've been mixing up `/O1` and `/Oi` options in `CMakeLists.txt`, which explains why those `__imp_*` fn's were missing in the x64 build after my latest changes. With both `/02` and `/Oi`, it appears to work in both x86 and x64!

**Comment by yupferris** [comment]
FWIW I _did_ get this to work by enabling MASM support and defining `fpuCos` for x64 (as inline assembly isn't supported by MSVC for x64), and in theory that could be made to work with cmake nicely, and also be conditionally included for x64 only. However, the resulting squished executable appears to be about 1kb larger than its `/01` counterpart. So simply choosing the optimization parameter based on the target architecture might actually be the "best" solution.

**Comment by yupferris** [comment]
Or, perhaps we can implement our own shift function in this case, just for x86. I think we can make a fair number of assumptions about the input parameters, and we can use inline asm, so we shouldn't incur any performance hits. In fact, just using SSE2 like the optimized version did is probably a great strategy.

**Comment by yupferris** [comment]
You know what, I don’t know why I didn’t think of it sooner - we can just use MMX intrinsics to implement the shifts in a way that matches what the optimized code was doing. This way we shouldn’t have to change any optimization opts or anything, and we’ll always get faster code regardless of x86/x64.
