### ISSUE TITLE
Investigate including VST3 SDK as a submodule

### ISSUE THREAD

**Issue by yupferris** [logicomacorp/WaveSabre#91]
This doesn't count as distribution as far as I'm aware, so long as our source releases don't actually include this source, we should be able to do this, which simplifies BYOSDK greatly.

**Comment by yupferris** [comment]
Unfortunately, we still need to support VST3 in order to do this (#89), as even the earliest [tagged VST3 SDK releases on Github](https://github.com/steinbergmedia/vst3sdk/tags) don't include any of the VST2 SDK code.

**Comment by emoon** [comment]
If this isn't possible then a "hack" would be to in a build setup use `wget/curl` or something like that to fetch and unpack it.

**Comment by yupferris** [comment]
Indeed, we should try to see if that works with [this archive link that we currently link to in our docs](https://web.archive.org/web/20200502121517/https://www.steinberg.net/sdk_downloads/vstsdk366_27_06_2016_build_61.zip), and if so, we could provide (platform-specific?) script(s) to set it up more easily.

**Comment by kusma** [comment]
submodules are notoriously hard to work with, and I would recommend against using them unless it provides a *lot* of benefit over something else.

It's the ugly duckling that was added to Git simply so KDE could convert their SVN repo that used svn:external heavily, but then nobody really gave it the love that was needed... It's not really something that should have been in Git in the first place IMO.

**Comment by emoon** [comment]
Yeah. For windows it would be possible to just include wget/curl and unzip inside a `bin` directory, and then have a `setup.cmd` `setup.sh` etc that just fetches it.

**Comment by emoon** [comment]
@kusma  In this case it might be ok if it's only to fetch the code and never update it, otherwise I agree

**Comment by emoon** [comment]
another problem tho with submodules is that *everyone* forgets to a `--recursive` when cloning. Now not a hard problem to fix, but it will be a constant question :)

**Comment by kusma** [comment]
@emoon: It's still pretty awkward to set up the project if you're not online or if github has problems, even if you have both repos already cloned. Submodules don't really do the "distributed" part of "distributed version control"...

**Comment by emoon** [comment]
Right

**Comment by emoon** [comment]
And yeah, I have opted to move away from submodules for most/all of my projects because in the end they are a PITA to work with.

**Comment by yupferris** [comment]
agreed about submodules; a custom script is likely much easier to use/work with.

**Comment by LeStahL** [comment]
It would be possible to use `file(DOWNLOAD ...)` and `file(ARCHIVE_EXTRACT ...)` in the CMakeLists.txt to get and unpack the VST3 SDK automatically - that saves the trouble of using scripts (or having the users download it manually).

**Comment by LeStahL** [comment]
Like this: https://github.com/logicomacorp/WaveSabre/pull/92 :)

**Comment by yupferris** [comment]
Fixed in #92
